services:
  nginx:
    build:
      context: ./docker/nginx
    restart: always
    ports:
      - "8081:80"

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      APP_TITLE: ${UNITMAN_APP_TITLE:-defaultTitle}
