services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/symfony
    restart: always
    ports:
      - "8081:80"

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/symfony
    environment:
      APP_TITLE: ${UNITMAN_APP_TITLE:-defaultTitle}
